import builtins from "builtin-modules"
import esbuild from "esbuild"
import { existsSync, watch } from "fs"
import fs from "fs/promises"
import path from "path"
import process from "process"
import { fileURLToPath } from "url"

const __dirname = fileURLToPath(new URL(".", import.meta.url))

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === "production"

// Determine entry point - prefer .ts if it exists, otherwise use .js
const entryPoint = existsSync("src/main.ts") ? "src/main.ts" : "src/main.js"

// Copy additional plugin files
async function copyPluginFiles() {
  try {
    // Copy manifest.json and styles.css to root
    await fs.copyFile("src/manifest.json", "manifest.json")

    // Copy styles.css if it exists
    try {
      await fs.copyFile("src/styles.css", "styles.css")
    } catch (error) {
      // styles.css doesn't exist, that's ok
    }

    console.info("Plugin files copied successfully")
  } catch (error) {
    console.error("Error copying plugin files:", error)
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [entryPoint],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  alias: {
    "@": path.resolve(__dirname, "src"),
  },
})

if (prod) {
  await context.rebuild()
  await copyPluginFiles()
  process.exit(0)
} else {
  // Initial copy of plugin files
  await copyPluginFiles()

  // Set up file watcher for the entire src directory
  const watcher = watch(
    "src",
    { recursive: true },
    async (eventType, filename) => {
      if (filename === "manifest.json" || filename === "styles.css") {
        await copyPluginFiles()
      }
    }
  )

  // Handle cleanup on process termination
  process.on("SIGINT", () => {
    watcher.close()
    context.dispose()
    process.exit(0)
  })

  // Start the watch mode
  await context.watch()
}
