import builtins from "builtin-modules"
import dotenv from "dotenv"
import esbuild from "esbuild"
import { existsSync, mkdirSync, watch } from "fs"
import fs from "fs/promises"
import path from "path"
import process from "process"
import { fileURLToPath } from "url"

// Load environment variables from .env file
dotenv.config()

const __dirname = fileURLToPath(new URL(".", import.meta.url))

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === "production"

// Determine entry point - prefer .ts if it exists, otherwise use .js
const entryPoint = existsSync("src/main.ts") ? "src/main.ts" : "src/main.js"

// Get output directory - use vault path in dev mode if provided, otherwise use root
const getOutputDir = () => {
  if (prod) {
    // Production builds always go to root
    return __dirname
  }

  const vaultPath = process.env.OBSIDIAN_VAULT_PATH
  if (vaultPath) {
    const pluginDir = path.join(vaultPath, ".obsidian", "plugins", "granola-sync")
    // Ensure plugin directory exists
    if (!existsSync(pluginDir)) {
      mkdirSync(pluginDir, { recursive: true })
    }
    return pluginDir
  }

  // Default to root if no vault path is provided
  return __dirname
}

const outputDir = getOutputDir()

// Copy additional plugin files
async function copyPluginFiles() {
  try {
    const manifestDest = path.join(outputDir, "manifest.json")
    await fs.copyFile("src/manifest.json", manifestDest)

    // Copy styles.css if it exists
    try {
      const stylesDest = path.join(outputDir, "styles.css")
      await fs.copyFile("src/styles.css", stylesDest)
    } catch (error) {
      // styles.css doesn't exist, that's ok
    }

    const dest = outputDir === __dirname ? "root" : outputDir
    console.info(`Plugin files copied successfully to ${dest}`)
  } catch (error) {
    console.error("Error copying plugin files:", error)
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [entryPoint],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outputDir, "main.js"),
  minify: prod,
  alias: {
    "@": path.resolve(__dirname, "src"),
  },
})

if (prod) {
  await context.rebuild()
  await copyPluginFiles()
  process.exit(0)
} else {
  // Initial copy of plugin files
  await copyPluginFiles()

  // Set up file watcher for the entire src directory
  const watcher = watch(
    "src",
    { recursive: true },
    async (eventType, filename) => {
      if (filename === "manifest.json" || filename === "styles.css") {
        await copyPluginFiles()
      }
    }
  )

  // Handle cleanup on process termination
  process.on("SIGINT", () => {
    watcher.close()
    context.dispose()
    process.exit(0)
  })

  // Start the watch mode
  await context.watch()
}
